$g_maillist = 'maillist.conf';
$g_generator = 'generator.pl';
$g_sendmail = 'sendmail.pl';
$g_tmpdir = '/tmp/';
$g_workers = 2;
$g_sendgrid_enabled = 1;
$g_gmail_enabled = 0;
$g_generatelist = 'auto_generate.conf';
$g_targetdir = '/var/www/';
1;
